inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: <%= RUBY_VERSION[/\d+\.\d+/] %>
  Exclude:
    - "bin/*"
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/version.rb
    - db/schema.rb
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - Gemfile
    - Rakefile

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 12

Naming/PredicateName:
  Enabled: false
